---
output: 
  html_document:
      keep_md: true
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# Choptank database

This website contains links and information for interacting with the Choptank Hydrologic Connectivity database, which uses the [ODM2](http://www.odm2.org/) framework and is an ongoing collaboration between several lab groups at the University of Maryland and Virginia Tech. Contact [Kelly Hondula](https://github.com/khondula) for more information. 

### Access

3 ways to connect to the database are

1. Log into [rstudio.sesync.org](https://rstudio.sesync.org/) with your sesync credentials and navigate to `/nfs/palmer-group-data/Choptank/choptank-db/connect.Rmd`.
2. Log into SESYNC VPN or be on the SESYNC research/private wifi network and use desktop RStudio to follow along [connecting to the database](https://palmerlab-umd.github.io/choptank-db/connect.html).
3. Download and use [pgAdmin 4](https://www.pgadmin.org/).


---

### Sites information

* [List of sites in database](https://palmerlab-umd.github.io/choptank-db/sites.html) *as of May 25, 2018*
* [Network of sites and site relationships](https://palmerlab-umd.github.io/choptank-db/sites-network.html) *as of May 25, 2018*
* [Map of survey points from March 13-15](https://palmerlab-umd.github.io/choptank-db/survey_pts.html)
* [Map of Nate's Approximate Well Locations](https://palmerlab-umd.github.io/choptank-db/ApproxWellLoc.html) 
*as of October 3, 2017*

### Samples

* [List of samples in database](https://palmerlab-umd.github.io/choptank-db/samples.html) *as of May 25, 2018*

### Methods

* [List of methods in database](https://palmerlab-umd.github.io/choptank-db/methods.html) *as of May 25, 2018*

---

### Guides

* [New Insert soil moisture data](https://palmerlab-umd.github.io/choptank-db/soil-moisture-notebook.nb.html)
* [Insert soil moisture data](https://palmerlab-umd.github.io/choptank-db/soil-moisture-measurements.html)

---

**Links**

* [View on Github](https://github.com/palmerlab-umd/choptank-db)
* [ODM2 Vocabulary](http://vocabulary.odm2.org/)
* [Schema diagrams](http://odm2.github.io/ODM2/schemas/ODM2_Current/diagrams/index.html)
